import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const base = 'http://127.0.0.1:3000'
const out = 'artifacts/ux-review'
fs.mkdirSync(out, { recursive: true })
const browser = await chromium.launch({ headless: true, channel: 'msedge' })
const products = await (await fetch(base + '/api/products')).json()
try {
  for (const width of [1440, 768, 390, 320]) {
    const page = await browser.newPage({ viewport: { width, height: 900 } })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(base)
    await page.locator('.product-card').first().waitFor()
    await page.evaluate(() => document.fonts.ready)
    assert.equal(await page.locator('.product-card').count(), Math.min(4, products.length))
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `home overflow ${width}`)
    await page.screenshot({ path: `${out}/home-${width}.png`, fullPage: true })
    await page.goto(base + '/catalogo?category=Hombre')
    await expect(page.getByRole('combobox', { name: 'Categoría', exact: true })).toHaveValue('Hombre')
    await page.getByLabel('Buscar perfume').fill('  AFNÁN  ')
    await expect(page).toHaveURL(/q=/)
    await expect(page.locator('.product-card')).toHaveCount(products.filter(p => p.category === 'Hombre').length)
    await page.reload(); await page.waitForLoadState('networkidle')
    await expect(page.getByLabel('Buscar perfume')).toHaveValue('AFNÁN')
    await page.locator('.product-card').first().click(); await page.waitForLoadState('networkidle')
    await page.getByRole('button', { name: 'Añadir a mi bolsa', exact: false }).click()
    await expect(page.getByRole('status')).toContainText('Añadido')
    await expect(page.getByRole('button', { name: 'Añadir otra unidad', exact: false })).toBeVisible()
    await page.screenshot({ path: `${out}/detail-${width}.png`, fullPage: true })
    await page.getByRole('link', { name: 'Volver a la colección', exact: false }).click()
    await expect(page.getByRole('combobox', { name: 'Categoría', exact: true })).toHaveValue('Hombre')
    await page.getByRole('button', { name: 'Limpiar filtros', exact: true }).click()
    await expect(page.locator('.product-card')).toHaveCount(products.length)
    await page.getByLabel('Buscar perfume').fill('no-existe-xyz')
    await expect(page.getByRole('heading', { name: 'No encontramos esa combinación.' })).toBeVisible()
    await page.getByRole('button', { name: 'Ver toda la colección' }).click()
    await expect(page.locator('.product-card')).toHaveCount(products.length)
    await page.getByRole('combobox', { name: 'Ordenar', exact: true }).selectOption('desc')
    await expect(page).toHaveURL(/sort=desc/)
    await page.screenshot({ path: `${out}/catalog-${width}.png`, fullPage: true })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `catalog overflow ${width}`)
    await page.goto(base + '/carrito')
    await expect(page.locator('.cart-row')).toHaveCount(1)
    await page.getByLabel('Cantidad').fill('999')
    await page.getByLabel('Cantidad').blur()
    await expect(page.getByLabel('Cantidad')).toHaveValue('99')
    await page.getByLabel('Cantidad').fill('1')
    await page.getByLabel('Cantidad').blur()
    await page.reload(); await page.waitForLoadState('networkidle')
    await expect(page.getByLabel('Cantidad')).toHaveValue('1')
    await page.route('**/api/settings', async route => {
      const response = await route.fetch()
      const settings = await response.json()
      await route.fulfill({ json: { ...settings, whatsapp: '573000000000' } })
    })
    await page.getByRole('button', { name: 'Preparar consulta por WhatsApp' }).click()
    await expect(page.getByRole('link', { name: 'Abrir WhatsApp' })).toBeVisible()
    assert.equal(await page.getByRole('button', { name: 'Preparar consulta por WhatsApp' }).count(), 0)
    await page.screenshot({ path: `${out}/cart-${width}.png`, fullPage: true })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `cart overflow ${width}`)
    await page.getByRole('button', { name: 'Modo oscuro', exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await page.goto(base)
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await page.screenshot({ path: `${out}/dark-${width}.png`, fullPage: true })
    assert.deepEqual(errors, [], `browser errors ${width}`)
    await page.close()
    console.log(`PASS ${width}px: layout, search, filters, return navigation, cart, quantity, persistence, WhatsApp link, theme`)
  }
} finally { await browser.close() }
